name: Get Deposits

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    env:
      API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
    steps:
      - name: Append bot data
        run: |-
          curl \
            -X GET \
              "$API_ENDPOINT"
